package greenDao.demo;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greenDao.demo.PictureLocation;

import greenDao.demo.PictureLocationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pictureLocationDaoConfig;

    private final PictureLocationDao pictureLocationDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pictureLocationDaoConfig = daoConfigMap.get(PictureLocationDao.class).clone();
        pictureLocationDaoConfig.initIdentityScope(type);

        pictureLocationDao = new PictureLocationDao(pictureLocationDaoConfig, this);

        registerDao(PictureLocation.class, pictureLocationDao);
    }
    
    public void clear() {
        pictureLocationDaoConfig.getIdentityScope().clear();
    }

    public PictureLocationDao getPictureLocationDao() {
        return pictureLocationDao;
    }

}
