package greenDao.greenDao.demo;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greenDao.greenDao.demo.FriendsList;

import greenDao.greenDao.demo.FriendsListDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig friendsListDaoConfig;

    private final FriendsListDao friendsListDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        friendsListDaoConfig = daoConfigMap.get(FriendsListDao.class).clone();
        friendsListDaoConfig.initIdentityScope(type);

        friendsListDao = new FriendsListDao(friendsListDaoConfig, this);

        registerDao(FriendsList.class, friendsListDao);
    }
    
    public void clear() {
        friendsListDaoConfig.getIdentityScope().clear();
    }

    public FriendsListDao getFriendsListDao() {
        return friendsListDao;
    }

}
